fullname_loc = '[name="name"]'
email_loc = '[name="email"]'
phone_loc = '[name="phone"]'
company_name_loc = '[name="company_name"]'
vat_loc = '[name="vat"]'
street_loc = '[name="street"]'
street2_loc = '[name="street2"]'
city_loc = '[name="city"]'
zip_loc = '[name="zip"]'
select_element_loc = '[name="country_id"]'
btn_checkout_loc = '.a-submit.a-submit-disable.a-submit-loading.btn.btn-primary.w-100.w-md-auto.order-1.order-md-3'
confirm_order_loc = '//h3[text()="Confirm order"]'
state_loc = '[name="state_id"]'
